# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'iOS example integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS example integration
  
  pod 'PPG_framework', :git => 'https://github.com/ppgco/ios-sdk'
  
  target 'PPGNotificationServiceExtension' do
    
    pod 'PPG_framework', :git => 'https://github.com/ppgco/ios-sdk'
  end

  target 'iOS example integrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS example integrationUITests' do
    # Pods for testing
  end

end
